FROM python:3.10-slim-buster

# Inside Container
# Make a new folder insde container
WORKDIR /backend-flask

# Outside Container -> Inside Container
# This contains the libraries we want to install to run the app
COPY requirements.txt requirements.txt

# Inside Container
# Install the python libraries used for the app
RUN pip3 install -r requirements.txt

# Outside Container -> Inside Container
# . means everything in current directory
# First period . - everything in /backend-flask (outside container)
# Second period . /backend-flask (inside container)
COPY . .

# Sent Environment Variables (Env Vars)
# Inside container and will remain set when the container is run
ENV FLASK_ENV=development

EXPOSE ${PORT}

# CMD = Command
# python3 -m flask run --host=0.0.0.0 --port=4567
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]